---

- block:
  - name: Create temporary directory for Aenea
    tempfile:
      path: "/home/{{ ansible_user | default(master_user, true) }}"
      state: directory
      suffix: _k8s_aeneabot
    register: k8s_aeneabot

  - name: "Upload ingress definitions to {{ k8s_aeneabot.path }}"
    become: yes
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ ansible_user | default(master_user, true) }}"
      group: "{{ ansible_user | default(master_user, true) }}"
    with_items:
      - { src: 'templates/aeneabot.j2', dest: '{{ k8s_aeneabot.path }}/aeneabot.yml' }

  - name: Run Aeneabot app
    k8s:
      namespace: default
      state: present
      src: "{{ k8s_aeneabot.path }}/aeneabot.yml"

  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_aeneabot.path }}"

  tags:
    - aeneabot