---

- block:
  - name: Create temporary directory for Impostor
    tempfile:
      path: "/home/{{ master_user }}"
      state: directory
      suffix: _k8s_impostor
    register: k8s_impostor

  - name: "Upload ingress definitions to {{ k8s_impostor.path }}"
    become: yes
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ master_user }}"
      group: "{{ master_group }}"
    with_items:
      - { src: 'templates/impostor.j2', dest: '{{ k8s_impostor.path }}/impostor.yml' }

  - name: Run Impostor app
    k8s:
      namespace: default
      state: present
      src: "{{ k8s_impostor.path }}/impostor.yml"

  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_impostor.path }}"

  tags:
    - impostor
