---
- block:
  # This is ugly, but helm module is broken
  - name: Create temporary directory for ingresses
    tempfile:
      path: "/home/{{ master_user }}"
      state: directory
      suffix: _k8s_deps
    register: k8s_deps

  - name: Download Jaeger definitions
    get_url:
      url: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: 'https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml', dest: '{{ k8s_deps.path }}/jaegertracing.io_jaegers_crd.yaml'}
      - { src: 'https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml', dest: '{{ k8s_deps.path }}/service_account.yaml'}
      - { src: 'https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml', dest: '{{ k8s_deps.path }}/role.yaml'}
      - { src: 'https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml', dest: '{{ k8s_deps.path }}/role_binding.yaml'}
      - { src: 'https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml', dest: '{{ k8s_deps.path }}/operator.yaml'}

  - name: "Upload Jaeger Deployment"
    become: yes
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ master_user }}"
      group: "{{ master_group }}"
    with_items:
      - { src: 'templates/jaeger.j2', dest: '{{ k8s_deps.path }}/jaeger.yaml' }

  - name: Create a Jaeger namespace
    k8s:
      name: observability
      api_version: v1
      kind: Namespace
      state: present

  - name: Deploy Jaeger
    k8s:
      namespace: observability
      src: "{{ item }}"
      state: present
    with_items:
      - "{{ k8s_deps.path }}/jaegertracing.io_jaegers_crd.yaml"
      - "{{ k8s_deps.path }}/role.yaml"
      - "{{ k8s_deps.path }}/role_binding.yaml"
      - "{{ k8s_deps.path }}/service_account.yaml"
      - "{{ k8s_deps.path }}/operator.yaml"
      - "{{ k8s_deps.path }}/jaeger.yaml"

  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_deps.path }}"

  tags:
    - jaeger