---
- block:
  # This is ugly, but helm module is broken
  - name: Create temporary directory for ingresses
    tempfile:
      path: "/home/{{ master_user }}"
      state: directory
      suffix: _k8s_deps
    register: k8s_deps

  - name: "Upload Jenkins Deployment"
    become: yes
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ master_user }}"
      group: "{{ master_group }}"
    with_items:
      - { src: 'templates/jenkins.j2', dest: '{{ k8s_deps.path }}/jenkins.yaml' }

  - name: Deploy Jenkins
    k8s:
      namespace: default
      src: "{{ item }}"
      state: present
    with_items:
      - "{{ k8s_deps.path }}/jenkins.yaml"

  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_deps.path }}"

  tags:
    - jenkins