---
- name: Deploy Traefik
  include_tasks: traefik.yml
  tags:
    - traefik

- name: Deploy Aena
  include_tasks: aenea.yml
  tags:
    - aenea

- name: Deploy Prometheus Bootstrap
  include_tasks: prometheus-bootstrap.yml
  tags:
    - prometheus_bootstrap

- name: Deploy Prometheus Config
  include_tasks: prometheus.yml
  tags:
    - prometheus

- name: Deploy Prometheus Node-Exporter
  include_tasks: prometheus.yml
  tags:
    - prometheus_node_exporter

- name: Deploy Alertmanager Config
  include_tasks: alertmanager.yml
  tags:
    - alertmanager

- name: Deploy Grafana
  include_tasks: grafana.yml
  tags:
    - grafana

- name: Deploy Sergio web service
  include_tasks: sergio.yml
  tags:
    - sergio

- name: Deploy PQMC Memorial
  include_tasks: pqmc.yml
  tags:
    - pqmc

- name: Deploy Raponchi Twitter tontuna
  include_tasks: raponchi.yml
  tags:
    - raponchi
