---
- name: Deploy Traefik
  include_tasks: traefik.yml
  tags:
    - traefik

- name: Deploy Aena
  include_tasks: aenea.yml
  tags:
    - aenea

- name: Deploy Sergio web service
  include_tasks: sergio.yml
  tags:
    - sergio

- name: Deploy PQMC Memorial
  include_tasks: pqmc.yml
  tags:
    - pqmc

- name: Deploy Raponchi Twitter tontuna
  include_tasks: raponchi.yml
  tags:
    - raponchi
