---
- block:
  # This is ugly, but helm module is broken
  - name: Create temporary directory for ingresses
    tempfile:
      path: "/home/{{ master_user }}"
      state: directory
      suffix: _k8s_deps
    register: k8s_deps

  - name: Download Metrics definitions
    get_url:
      url: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: 'https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.6/components.yaml', dest: '{{ k8s_deps.path }}/metrics.yaml'}

  - name: Deploy Metrics
    k8s:
      namespace: kube-system
      src: "{{ item }}"
      state: present
    with_items:
      - "{{ k8s_deps.path }}/metrics.yaml"

  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_deps.path }}"

  tags:
    - metrics