---
- block:
  # This is ugly, but helm module is broken
  - name: Create temporary directory for ingresses
    tempfile:
      path: "/home/{{ master_user }}"
      state: directory
      suffix: _k8s_deps
    register: k8s_deps

  - name: Upload Nginx deploy template
    template:
      src: templates/nginx-deploy.j2
      dest: "{{ k8s_deps.path }}/nginx-deploy.yaml"

  - name: Deploy Nginx
    k8s:
      namespace: ingress-nginx
      src: "{{ k8s_deps.path }}/nginx-deploy.yaml"
      state: present
  
  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_deps.path }}"

  tags:
    - nginx