---
- block:
  # This is ugly, but helm module is broken
  - name: Create temporary directory for ingresses
    tempfile:
      path: "/home/{{ master_user }}"
      state: directory
      suffix: _k8s_deps
    register: k8s_deps

  - name: Ensure PQMC Deployment content path exists
    become: yes
    file:
      path: /mnt/pqmc-web
      state: directory
      owner: 1001
      group: 1001
      mode: 0755

  - name: Deploy PQMC Content
    become: yes
    copy:
      src: kube-apps/pqmc-web/content/
      dest: /mnt/pqmc-web
      force: yes
      owner: 1001
      group: 1001
      mode: 0755


  - name: "Upload PQMC Deployment"
    become: yes
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ master_user }}"
      group: "{{ master_group }}"
    with_items:
      - { src: 'templates/pqmc.j2', dest: '{{ k8s_deps.path }}/pqmc.yaml' }

  - name: Deploy PQMC
    k8s:
      namespace: default
      src: "{{ item }}"
      state: present
    with_items:
      - "{{ k8s_deps.path }}/pqmc.yaml"

  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_deps.path }}"

  tags:
    - pqmc