---
- block:
  - name: Create temporary directory for ingresses
    tempfile:
      path: "/home/{{ master_user }}"
      state: directory
      suffix: _k8s_ingress
    register: k8s_ingress

  - name: "Upload ingress definitions to {{ k8s_ingress.path }}"
    become: yes
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ master_user }}"
      group: "{{ master_group }}"
    with_items:
      - { src: 'files/helloworld.yml', dest: '{{ k8s_ingress.path }}/helloworld.yml' }
      - { src: 'files/default-ingress.yml', dest: '{{ k8s_ingress.path }}/default-ingress.yml' }

  - name: Run helloworld app
    k8s:
      namespace: default
      state: present
      src: "{{ k8s_ingress.path }}/helloworld.yml"

  - name: Create ingress for helloworld
    k8s:
      namespace: default
      state: present
      src: "{{ k8s_ingress.path }}/default-ingress.yml"

  always:
    - name: Tempdir cleanup
      file:
        state: absent
        path: "{{ k8s_ingress.path }}"

  tags:
    - default-ingress