# Default values for ygdrassil-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: ygdrassil-monitoring
# Decide expose services using TLS or not
serviceSchema: "https"
## Prometheus
prometheusUrl: prometheus.proyectopqmc.com
## Alertmanager
alertmanagerUrl: alertmanager.proyectopqmc.com
## Grafana
grafanaUrl: grafana.proyectopqmc.com
## OpenSearch
opensearchUrl: opensearch.proyectopqmc.com
opensearchDashboardUrl: dashboard.proyectopqmc.com
## Prometheus Targets
prometheus:
  alertmanager:
    persistence:
      enabled: false
  server:
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      runAsGroup: 65534
      fsGroup: 1000
    persistentVolume:
      existingClaim: ygdrassil-monitoring-prometheus-server
  extraScrapeConfigs: |
    - job_name: aeneabot-exporter
      scrape_interval: 2s
      params:
        module: [http_2xx]
      metrics_path: /
      static_configs:
        - targets:
          - http://aeneabot-svc.aeneabot.svc.cluster.local:9900
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: aeneabot-svc.aeneabot.svc.cluster.local:9900
    - job_name: raponchi-exporter
      scrape_interval: 2s
      params:
        module: [http_2xx]
      metrics_path: /
      static_configs:
        - targets:
          - http://raponchi-prometheus-svc.raponchi.svc.cluster.local:10090
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: raponchi-prometheus-svc.raponchi.svc.cluster.local:10090
grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://monitoring-prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true

opensearch:
  persistence:
    enabled: true
  singleNode: true
